[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "^23.0.0"
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
